using System;
using System.Globalization;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Forms=System.Windows.Forms;
namespace CodexGlass {
sealed partial class GlassWindow {
    string draftAccount,draftKind="renewal";DateTime? draftDate;bool draftReady;
    UIElement SettingRow(string label,UIElement control,string help=null){var text=Stack(Text(label,12),help==null?null:Text(help,10,muted));if(help!=null)((FrameworkElement)text.Children[1]).Margin=new Thickness(0,5,0,0);var el=control as FrameworkElement;if(el!=null){el.Margin=new Thickness(14,0,0,0);el.VerticalAlignment=VerticalAlignment.Center;}var row=Row(text,control);row.Margin=new Thickness(0,11,0,11);return row;}
    ComboBox Combo(string[] values,string[] names,string selected,Action<string> change){var combo=new ComboBox{Width=114,FontSize=11,Padding=new Thickness(6,5,6,5)};for(int i=0;i<values.Length;i++)combo.Items.Add(new ComboBoxItem{Content=names[i],Tag=values[i]});combo.SelectedIndex=Math.Max(0,Array.IndexOf(values,selected));combo.SelectionChanged+=(s,e)=>{var item=combo.SelectedItem as ComboBoxItem;if(item!=null)change((string)item.Tag);};return combo;}
    UIElement Toggle(string key,string help){var check=new CheckBox{IsChecked=J.B(Service.Settings,key),Style=(Style)Resources["Switch"]};check.Checked+=(s,e)=>ChangeBool(key,true);check.Unchecked+=(s,e)=>ChangeBool(key,false);return SettingRow(T(key),check,T(help));}
    void ChangeBool(string key,bool value){Service.Settings[key]=value;if(key=="startup")SetStartup(value);Service.Save();}
    void Section(StackPanel p,string label,UIElement content){var h=Text(label,11,muted,true);h.Margin=new Thickness(0,10,0,8);p.Children.Add(h);var card=Card(content);card.Padding=new Thickness(12,0,12,0);p.Children.Add(card);}
    UIElement SettingsView(){var panel=new StackPanel();
        var appearance=Stack(SettingRow(T("language"),Combo(Localization.Codes,Localization.Names,J.S(Service.Settings,"language"),SetLanguage)),Divider(),SettingRow(T("theme"),Combo(new[]{"light","dark","system"},new[]{T("light"),T("dark"),T("system")},J.S(Service.Settings,"theme"),v=>{Service.Settings["theme"]=v;Service.Save();Render();})));Section(panel,T("appearance"),appearance);
        var pick=Button("●",()=>{using(var dialog=new Forms.ColorDialog()){var c=((SolidColorBrush)accent).Color;dialog.Color=System.Drawing.Color.FromArgb(c.R,c.G,c.B);dialog.FullOpen=true;if(dialog.ShowDialog()==Forms.DialogResult.OK){Service.Settings["accentColor"]="#"+dialog.Color.R.ToString("x2")+dialog.Color.G.ToString("x2")+dialog.Color.B.ToString("x2");Service.Save();Render();}}},accent);pick.Content=new System.Windows.Shapes.Rectangle{Width=24,Height=24,RadiusX=4,RadiusY=4,Fill=accent};pick.Width=42;var colorRow=SettingRow(T("accentColor"),pick,T("accentHelp"));var presets=new WrapPanel{Margin=new Thickness(0,0,0,12)};foreach(string color in new[]{"#4c8df3","#8b5cf6","#16a085","#ed7896","#f59e0b","#64748b"}){string selected=color;var b=Button("●",()=>{Service.Settings["accentColor"]=selected;Service.Save();Render();},Paint.Brush(color));b.Content=new System.Windows.Shapes.Ellipse{Width=20,Height=20,Fill=Paint.Brush(color)};b.Width=30;b.Padding=new Thickness(0);b.ToolTip=color;presets.Children.Add(b);}var reset=Button(T("resetAccent"),()=>{Service.Settings["accentColor"]=null;Service.Save();Render();});reset.FontSize=10;presets.Children.Add(reset);Section(panel,T("accentColor"),Stack(colorRow,presets));
        Section(panel,T("ringSettings"),Stack(SettingRow(T("ringWindow"),Combo(new[]{"auto","five","week"},new[]{T("auto"),T("five"),T("week")},J.S(Service.Settings,"ringWindow"),v=>{Service.Settings["ringWindow"]=v;Service.Save();}),T("ringWindowHelp")),Divider(),Toggle("elapsedArc","elapsedArcHelp")));
        Section(panel,T("behavior"),Stack(Toggle("startup","startupHelp"),Divider(),Toggle("notifications","notificationsHelp"),Divider(),SettingRow(T("interval"),Combo(new[]{"60","120","300","600"},new[]{T("everyMinute"),T("every2"),T("every5"),T("every10")},J.N(Service.Settings,"refreshSeconds").ToString(),v=>{Service.Settings["refreshSeconds"]=int.Parse(v);Service.Save();}))));
        var membership=new StackPanel();if(Service.Identity==null){var note=Text(T("connectFirst"),11,muted);note.Margin=new Thickness(0,16,0,16);membership.Children.Add(note);}else{
            if(!draftReady||draftAccount!=Service.Identity){draftReady=true;draftAccount=Service.Identity;string saved=J.S(Service.Member,"date");draftDate=J.Date(saved)?(DateTime?)DateTime.ParseExact(saved,"yyyy-MM-dd",CultureInfo.InvariantCulture):null;draftKind=J.S(Service.Member,"kind","renewal");}
            var help=Text(T("memberHelp"),10,muted);help.Margin=new Thickness(0,16,0,8);membership.Children.Add(help);membership.Children.Add(SettingRow(T("dateKind"),Combo(new[]{"renewal","expiry"},new[]{T("renewal"),T("expiry")},draftKind,v=>draftKind=v)));membership.Children.Add(Divider());
            var date=new DatePicker{Foreground=Paint.Brush("#1E2D45"),Background=Paint.Brush("#FAFCFF"),SelectedDate=draftDate,Width=132,FontSize=11,DisplayDateStart=new DateTime(2020,1,1),DisplayDateEnd=new DateTime(2100,12,31)};date.SelectedDateChanged+=(s,e)=>draftDate=date.SelectedDate;membership.Children.Add(SettingRow(T("date"),date));
            var status=Text("",10,muted);var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(0,4,0,12)};actions.Children.Add(Button(T("clear"),()=>{if(Service.SetMember(draftAccount,"","renewal")){draftDate=null;date.SelectedDate=null;status.Text=T("saved");}else status.Text=T("accountChanged");}));actions.Children.Add(Button(T("save"),()=>{status.Text=T(!draftDate.HasValue?"invalidDate":Service.SetMember(draftAccount,draftDate.Value.ToString("yyyy-MM-dd"),draftKind)?"saved":"accountChanged");}));membership.Children.Add(status);membership.Children.Add(actions);
        }Section(panel,T("membership")+" · "+T("manual"),membership);var privacy=Text(T("privacy"),11,muted);privacy.Margin=new Thickness(0,16,0,16);Section(panel,T("account"),privacy);panel.Children.Add(Row(Button(T("usage")+" ↗",()=>Open("https://chatgpt.com/codex/settings/usage")),Button(T("quit"),Quit)));panel.Children.Add(Button(T("licenses"),()=>{var licenses=new Window{Title="Codex Glass · Licenses",Owner=this,Width=620,Height=600,WindowStartupLocation=WindowStartupLocation.CenterOwner,Content=new TextBox{Text=Resource("LICENSE")+"\n\n"+Resource("NOTICES")+"\n\n"+Resource("APACHE"),IsReadOnly=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(20)}};licenses.ShowDialog();}));var disclaimer=Text(T("developer"),10,muted);disclaimer.Margin=new Thickness(0,18,0,10);panel.Children.Add(disclaimer);return panel;
    }
}
}
