using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using D=System.Collections.Generic.Dictionary<string,object>;
namespace CodexGlass {
static class NativeTests {
    static int checks;
    public static void Check(bool test,string description){checks++;if(!test)throw new Exception(description);}
    public static void Run(){
        Localization.Validate();Check(true,"All three language catalogs have identical keys");
        Check(J.S(Model.Settings(J.Obj("language","zh-TW")),"language")=="zh-TW","Traditional language preference persists");
        Check(Localization.Text("zh-TW","week")=="本週"&&Localization.Text("zh-TW","settings")=="設定","Traditional interface strings");
        Check(new DateTime(2026,9,20).ToString("MMM d, yyyy",Localization.Culture("en"))=="Sep 20, 2026","English dates ignore Windows regional language");
        var fixture=J.Obj("account",J.Obj("email","a@example.invalid","planType","prolite"),"result",J.Obj("rateLimitsByLimitId",J.Obj("codex",J.Obj("primary",J.Obj("usedPercent",23,"windowDurationMins",10080,"resetsAt",20000)),"reserve",J.Obj("primary",J.Obj("usedPercent",99,"windowDurationMins",10080,"resetsAt",20000)))));
        var a=J.Get(fixture,"account");var s=Model.Normalize(a,fixture["result"],1000);var windows=J.Items(s["windows"]).ToArray();Check(windows.Length==2,"All quota pools preserved");Check(J.N(windows[0],"minutes")==10080,"Weekly primary correctly identified");Check(J.N(windows[0],"remaining")==77,"Remaining calculated");Check(J.N(Model.Selected(s,"auto",1000),"remaining")==77,"Reserve excluded from ring");Check(J.N(Model.Selected(s,"five",1000),"remaining")==77,"Pinned missing window falls back");Check(Model.Plan("prolite")=="Pro","Plan alias");Check(Model.Plan("custom")=="custom","Unknown plan retained");Check(J.Get(J.Get(s,"resets"),"count")==null,"Missing reset count stays unknown");
        var zero=Model.Normalize(a,J.Obj("rateLimits",J.Obj("primary",J.Obj("usedPercent",100,"windowDurationMins",300)),"rateLimitResetCredits",J.Obj("availableCount",0)),1000);Check(J.N(Model.Selected(zero,"auto",1000),"remaining")==0,"Actual zero preserved");Check(J.N(J.Get(zero,"resets"),"count",-1)==0,"Zero reset preserved");Check(Model.Cache(s,"other",2000)==null,"Cache account boundary");Check(Model.Cache(s,J.S(s,"identity"),86401001)==null,"Cache expires");Check(Model.Cache(s,J.S(s,"identity"),30000000)==null,"Expired quota removed");
        var u=Model.Usage(J.Obj("dailyUsageBuckets",new[]{J.Obj("startDate","2026-09-18","tokens",0),J.Obj("startDate","2026-09-19","tokens",10),J.Obj("startDate","2026-09-19","tokens",10),J.Obj("startDate","2026-09-17","tokens",12),J.Obj("startDate","2026-09-17","tokens",13),J.Obj("startDate","2026-02-30","tokens",2),J.Obj("startDate","2026-09-16","tokens",-1)}),1000);
        Check(J.Items(u["days"]).Count()==2,"Duplicate/conflicting/invalid dates excluded");Check(J.B(u,"incomplete"),"Partial data labeled");var days=Model.Series(u,7,new DateTime(2026,9,20));Check(days.Count==7&&J.Get(days[6],"tokens")==null,"Missing days remain null");Check(J.N(days[4],"tokens",-1)==0,"Zero differs from missing day");Check(J.S(days[0],"date")=="2026-09-14","Ascending calendar range");Check(Model.Series(u,30,new DateTime(2026,3,1))[0]["date"].ToString()=="2026-01-31","Month boundary");
        var prefs=Model.Settings(J.Obj("mainSize",J.Obj("width",1,"height",9000),"accentColor","#AB12EF","language","bad","membership",J.Obj(J.S(s,"identity"),J.Obj("date","2026-02-30","kind","expiry"))));Check(J.N(prefs["mainSize"],"width")==320&&J.N(prefs["mainSize"],"height")==1400,"Saved window constraints");Check(J.S(prefs,"accentColor")=="#ab12ef"&&J.S(prefs,"language")=="zh","Settings sanitization");Check(J.Map(prefs["membership"]).Count==0,"Invalid membership date discarded");Check(Model.Identity(a)!=Model.Identity(J.Obj("email","b@example.invalid")),"Identity isolation");
        string folder=Path.Combine(Program.QaDirectory,"test-storage");var store=new Store(folder);store.Write("settings",prefs);store.Write("settings",Model.Settings(store.Read("settings")));Check(J.S(store.Read("settings"),"accentColor")=="#ab12ef","Atomic settings round trip");
        TestRpc().GetAwaiter().GetResult();File.WriteAllText(Path.Combine(Program.QaDirectory,"self-test.json"),J.Json(J.Obj("passed",checks,"failed",0)));
    }
    static async Task TestRpc(){string previous=Environment.GetEnvironmentVariable("CODEX_GLASS_CODEX_PATH");string fake=Environment.GetEnvironmentVariable("CODEX_GLASS_TEST_RPC");Environment.SetEnvironmentVariable("CODEX_GLASS_CODEX_PATH",Assembly.GetExecutingAssembly().Location);Environment.SetEnvironmentVariable("CODEX_GLASS_TEST_RPC","1");try{using(var rpc=new Rpc()){var results=await Task.WhenAll(rpc.Call("account/read"),rpc.Call("account/rateLimits/read"));Check(J.S(J.Get(results[0],"account"),"type")=="chatgpt","RPC handshake and correlation");Check(J.Get(results[1],"rateLimits")!=null,"Concurrent response correlation");int child=rpc.ChildId;Check(child>0,"Helper started");rpc.Stop();await Task.Delay(100);Check(rpc.ChildId==0,"Helper is released after read");bool gone;try{gone=Process.GetProcessById(child).HasExited;}catch{gone=true;}Check(gone,"Helper process actually exits");var again=await rpc.Call("account/read");Check(J.S(J.Get(again,"account"),"type")=="chatgpt","Helper restarts on demand");bool rejected=false;try{await rpc.Call("test/eof");}catch{rejected=true;}Check(rejected&&rpc.ChildId==0,"EOF rejects pending call without busy loop");await rpc.Call("account/read");var held=new[]{rpc.Call("test/hold"),rpc.Call("test/hold"),rpc.Call("test/hold")};await Task.Delay(50);rpc.Stop();foreach(var request in held){bool canceled=false;try{await request;}catch{canceled=true;}Check(canceled,"Stopping helper rejects each concurrent pending call");}Check(rpc.ChildId==0,"Stopped helper stays released");}}finally{Environment.SetEnvironmentVariable("CODEX_GLASS_CODEX_PATH",previous);Environment.SetEnvironmentVariable("CODEX_GLASS_TEST_RPC",fake);}}
    public static void FakeRpc(){string line;while((line=Console.ReadLine())!=null){var m=J.Parse(line);string method=J.S(m,"method");if(method=="test/eof")return;if(method=="test/hold")continue;if(J.Get(m,"id")==null)continue;object result=method=="account/read"?J.Obj("account",J.Obj("type","chatgpt","email","fixture@example.invalid")):method=="account/rateLimits/read"?J.Obj("rateLimits",J.Obj("primary",J.Obj("usedPercent",25,"windowDurationMins",10080))):new D();Console.WriteLine(J.Json(J.Obj("id",J.Get(m,"id"),"result",result)));}}
}
sealed partial class GlassWindow {
    async Task Capture(string name){await Dispatcher.InvokeAsync(()=>{},DispatcherPriority.ApplicationIdle);UpdateLayout();var visual=Content as FrameworkElement;var image=new RenderTargetBitmap((int)Math.Ceiling(Width),(int)Math.Ceiling(Height),96,96,PixelFormats.Pbgra32);image.Render(this);var pixels=new byte[(int)Math.Ceiling(Width)*(int)Math.Ceiling(Height)*4];image.CopyPixels(pixels,(int)Math.Ceiling(Width)*4,0);if(!Enumerable.Range(0,pixels.Length/4).Any(i=>pixels[i*4+3]>0))throw new Exception("Blank capture: "+name);var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(image));using(var file=File.Create(Path.Combine(Program.QaDirectory,name+".png")))png.Save(file);}
    async Task Pause(){await Task.Delay(80);await Dispatcher.InvokeAsync(()=>{},DispatcherPriority.ApplicationIdle);}
    async Task CheckLanguages(){
        foreach(string code in Localization.Codes){
            await Pause();
            var button=Descendants<Button>(this).Single(b=>System.Windows.Automation.AutomationProperties.GetName(b)==T("language"));
            var menu=LanguageMenu(button);NativeTests.Check(menu.Items.Count==3,"Language popup has three choices");
            NativeTests.Check(menu.Items.Cast<MenuItem>().Count(i=>i.IsChecked)==1,"Language popup marks one current language");
            menu.IsOpen=true;await Pause();
            var image=new RenderTargetBitmap((int)Math.Ceiling(menu.ActualWidth),(int)Math.Ceiling(menu.ActualHeight),96,96,PixelFormats.Pbgra32);image.Render(menu);var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(image));using(var file=File.Create(Path.Combine(Program.QaDirectory,"language-menu.png")))png.Save(file);
            var item=(MenuItem)menu.Items[Array.IndexOf(Localization.Codes,code)];item.RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));menu.IsOpen=false;await Pause();
            NativeTests.Check(J.S(Service.Store.Read("settings"),"language")==code,"Menu language persists: "+code);
            NativeTests.Check(Descendants<TextBlock>(this).Any(t=>t.Text==T("title")),"Overview translated: "+code);
            await Capture(code+"-locale-main");view="settings";Render();await Capture(code+"-locale-settings");view="main";Render();
        }
        SetLanguage("zh");
    }
    async Task CaptureReadme(){
        await Service.Refresh();Service.Snapshot["windows"]=J.Items(Service.Snapshot["windows"]).Where(q=>J.S(q,"group")!="codex"||J.N(q,"minutes")==10080).ToArray();
        view="main";dailyOpen=otherOpen=false;Service.Settings["mainSize"]=null;Service.Settings["compact"]=false;Service.Settings["theme"]="light";Service.Settings["accentColor"]="#4c8df3";
        foreach(string code in Localization.Codes){SetLanguage(code);scroller.ScrollToTop();await Capture("publish-"+code);}
        Service.Settings["theme"]="dark";Render();await Capture("publish-dark");Compact(true);await Capture("publish-mini");
    }
    void CheckTitleBar(){UpdateLayout();var header=Descendants<Border>(this).Single(b=>b.Name=="TitleBar");
        foreach(var point in new[]{new Point(5,28),new Point(header.ActualWidth/2,5),new Point(header.ActualWidth-5,28)}){
            var hit=InputHitTest(header.TranslatePoint(point,this)) as DependencyObject;
            NativeTests.Check(HeaderDragTarget(hit,header),"Title bar blank space accepts dragging");
        }
        foreach(var element in Descendants<Image>(header).Cast<FrameworkElement>().Concat(Descendants<TextBlock>(header).Where(t=>t.Text=="Codex Glass"))){
            var hit=InputHitTest(element.TranslatePoint(new Point(element.ActualWidth/2,element.ActualHeight/2),this)) as DependencyObject;
            NativeTests.Check(HeaderDragTarget(hit,header),"Logo/title accepts dragging");
        }
        foreach(var button in Descendants<Button>(header)){
            var hit=InputHitTest(button.TranslatePoint(new Point(button.ActualWidth/2,button.ActualHeight/2),this)) as DependencyObject;
            NativeTests.Check(!HeaderDragTarget(hit,header),"Header button stays clickable");
        }
        var oldContent=Content;moving=true;Render();NativeTests.Check(Content==oldContent&&renderAfterMove,"Refresh deferred during window drag");moving=false;renderAfterMove=false;Render();
    }
    public async Task RunQA(){await Pause();await Service.Refresh();Render();await Capture("zh-main");CheckTitleBar();await CheckLanguages();double closedHeight=Height;otherOpen=true;Render();await Pause();NativeTests.Check(Height==closedHeight&&scroller.ScrollableHeight>0,"Expanding pools scrolls without growing the window");NativeTests.Check(Descendants<TextBlock>(scroller).Any(t=>t.Text=="gpt-5.6-luna"),"Pool model label is shown");var bar=Descendants<System.Windows.Controls.Primitives.ScrollBar>(scroller).Single(b=>b.Name=="PART_VerticalScrollBar");NativeTests.Check(bar.IsVisible,"Right scrollbar visible for overflow");System.Windows.Controls.Primitives.ScrollBar.PageDownCommand.Execute(null,bar);await Pause();NativeTests.Check(scroller.VerticalOffset>0,"Scrollbar page-down scrolls content");scroller.ScrollToVerticalOffset(250);await Pause();double beforeRefresh=scroller.VerticalOffset;Render();await Pause();NativeTests.Check(Math.Abs(scroller.VerticalOffset-beforeRefresh)<1,"Refresh retains scroll position");await Capture("zh-other-pools");Service.Settings["mainSize"]=J.Obj("width",320,"height",760);Render();scroller.ScrollToEnd();await Capture("zh-other-pools-narrow");Service.Settings["language"]="en";Render();scroller.ScrollToEnd();await Capture("en-other-pools-narrow");Service.Settings["language"]="zh";Service.Settings["mainSize"]=null;otherOpen=false;dailyOpen=true;await Service.ReadDaily();Render();await Pause();NativeTests.Check(Height==closedHeight,"Daily usage expansion keeps main height");await Capture("zh-daily");range=30;Render();await Capture("zh-month");NativeTests.Check(Descendants<BarChart>(this).Single().Days.Count==30,"Thirty chart bars");
        var initial=new Rect(Left,Top,Width,Height);foreach(string corner in new[]{"se","sw","ne","nw"}){var origin=new Rect(Left,Top,Width,Height);manualResize=true;ResizeFrom(origin,corner,corner.Contains("w")?10:-10,corner.Contains("n")?10:-10);manualResize=false;NativeTests.Check(Math.Abs(Width-origin.Width+10)<.1&&Math.Abs(Height-origin.Height+10)<.1,"Corner sizing "+corner);}
        Service.Settings["mainSize"]=J.Obj("width",320,"height",420);Service.Save();Render();await Capture("small");await Pause();NativeTests.Check(scroller.ScrollableHeight>0&&scroller.ScrollableWidth==0,"Narrow overview scrolls vertically only");scroller.ScrollToEnd();await Capture("small-footer");Compact(true);await Capture("mini");NativeTests.Check(Width==92&&Height==126,"Mini dimensions preserved");NativeTests.Check(J.N(ring.Quota,"remaining")==68,"Ring tracks primary allowance");Service.Settings["ringWindow"]="week";Service.Settings["elapsedArc"]=true;Render();await Capture("mini-week");Background=Brushes.White;await Capture("mini-white-wallpaper");Background=Paint.Brush("#F1F4F8");await Capture("mini-light-wallpaper");Background=Paint.Brush("#17243A");await Capture("mini-dark-wallpaper");Background=Brushes.Transparent;NativeTests.Check(J.N(ring.Quota,"remaining")==82&&ring.Period==T("week"),"Pinned weekly ring");Compact(false);NativeTests.Check(Width==320&&Height==420,"Main size restored");view="settings";Render();await Capture("zh-settings");NativeTests.Check(Descendants<ComboBox>(this).Count()>=5,"Native settings controls present");
        Service.Settings["language"]="en";Service.Settings["theme"]="dark";Service.Settings["accentColor"]="#8b5cf6";Service.Save();Render();await Capture("en-settings");NativeTests.Check(Service.SetMember(Service.Identity,"2027-03-14","expiry"),"Member saved");NativeTests.Check(!Service.SetMember("wrong","2027-03-14","expiry"),"Membership cross-account rejected");NativeTests.Check(J.S(Service.Store.Read("settings"),"accentColor")=="#8b5cf6","Color persists");view="main";Service.Settings["mainSize"]=null;Render();await Capture("en-dark");Compact(true);var memory=Memory();await Capture("mini-dark");Service.Snapshot=null;Service.Status="error";Service.Error="signInRequired";Compact(false);Render();await Capture("signed-out");NativeTests.Check(Descendants<Button>(this).Any(b=>Convert.ToString(b.Content)==T("connect")),"Sign-in control available");await CaptureReadme();File.WriteAllText(Path.Combine(Program.QaDirectory,"ui-result.json"),J.Json(J.Obj("passed",true,"renderer","WPF","miniWidth",92,"miniHeight",126,"helperRunning",Service.Rpc.ChildId!=0,"memory",memory)));
    }
    static IEnumerable<T> Descendants<T>(DependencyObject root) where T:DependencyObject {for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++){var child=VisualTreeHelper.GetChild(root,i);if(child is T)yield return (T)child;foreach(var next in Descendants<T>(child))yield return next;}}
    static D Memory(){using(var p=Process.GetCurrentProcess()){p.Refresh();return J.Obj("workingSetBytes",p.WorkingSet64,"privateBytes",p.PrivateMemorySize64);}}
    public async Task MeasureLive(){Service.Settings["compact"]=false;view="main";Render();while(Service.Busy)await Task.Delay(100);await Service.Refresh();await Task.Delay(2000);var main=Memory();if(Array.IndexOf(Program.Arguments,"--measure-screenshots")>=0)await Capture("live-main");dailyOpen=true;await Service.ReadDaily();Render();await Task.Delay(1000);if(Array.IndexOf(Program.Arguments,"--measure-screenshots")>=0)await Capture("live-daily");var chart=Memory();Compact(true);await Task.Delay(2000);var mini=Memory();File.WriteAllText(Path.Combine(Program.QaDirectory,"live-result.json"),J.Json(J.Obj("status",Service.Status,"error",Service.Error,"dailyError",Service.DailyError,"dailyCount",J.Items(J.Get(Service.Daily,"days")).Count(),"main",main,"chart",chart,"mini",mini,"helperRunning",Service.Rpc.ChildId!=0,"version",Version)));}
}
}
