using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Microsoft.Win32;
using Forms=System.Windows.Forms;
using D=System.Collections.Generic.Dictionary<string,object>;
namespace CodexGlass {
sealed partial class GlassWindow : Window {
    public readonly Service Service;readonly bool smoke;Forms.NotifyIcon tray;DispatcherTimer poll,tick,loginTimeout,moveTimer;string view="main";bool dailyOpen,otherOpen,placing,manualResize,closing;int range=7;Brush ink,muted,accent,line,surface;bool dark;Geometry logo;Point ringDown;bool ringMoved;RingView ring;TextBlock statusText;List<Action> clockUpdates=new List<Action>();ScrollViewer scroller;
    public const string Version="0.5.0";
    public GlassWindow(Service service,bool qa){Service=service;smoke=qa;logo=Geometry.Parse(Resource("logo.txt"));logo.Freeze();
        Title="Codex Glass";FontFamily=new FontFamily("Segoe UI, Microsoft YaHei");FontSize=12;WindowStyle=WindowStyle.None;AllowsTransparency=true;Background=Brushes.Transparent;ShowInTaskbar=false;ResizeMode=ResizeMode.NoResize;Width=382;Height=580;UseLayoutRounding=true;SnapsToDevicePixels=true;
        using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("icon.png")){Icon=BitmapFrame.Create(stream,BitmapCreateOptions.None,BitmapCacheOption.OnLoad);}
        var styles=(ResourceDictionary)System.Windows.Markup.XamlReader.Parse(Resource("styles.xaml"));Resources.MergedDictionaries.Add(styles);
        tray=new Forms.NotifyIcon{Text="Codex Glass",Visible=!qa};using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream("icon.ico"))tray.Icon=new System.Drawing.Icon(s);
        tray.MouseClick+=(s,e)=>{if(e.Button==Forms.MouseButtons.Left)Dispatcher.BeginInvoke(new Action(()=>{if(IsVisible)Hide();else Reveal();}));};tray.BalloonTipClicked+=(s,e)=>Dispatcher.BeginInvoke(new Action(Reveal));
        Service.Alert=text=>Dispatcher.BeginInvoke(new Action(()=>{if(!smoke)tray.ShowBalloonTip(7000,"Codex Glass",text,Forms.ToolTipIcon.Info);}));
        Service.Changed=()=>{if(!Dispatcher.CheckAccess()){Dispatcher.BeginInvoke(new Action(OnServiceChanged));return;}OnServiceChanged();};
        Service.RpcNotice=(method,p)=>Dispatcher.BeginInvoke(new Action(async()=>{if(closing)return;if(method=="account/login/completed"&&J.S(p,"loginId")==Service.LoginId){Service.LoginId=null;loginTimeout.Stop();await Service.Refresh();}}));
        poll=new DispatcherTimer();poll.Tick+=async(s,e)=>{poll.Stop();await Service.Refresh();};
        tick=new DispatcherTimer{Interval=TimeSpan.FromSeconds(15)};tick.Tick+=(s,e)=>{foreach(var update in clockUpdates)update();if(ring!=null){var selected=Model.Selected(Service.Snapshot,J.S(Service.Settings,"ringWindow"),J.Now);ring.Quota=selected;ring.Period=selected==null?"":QuotaName(selected);ring.InvalidateVisual();}if(Service.Snapshot!=null&&J.Items(J.Get(Service.Snapshot,"windows")).Any(w=>J.N(w,"resetsAt")>0&&J.N(w,"resetsAt")<=J.Now)&&!Service.Busy)RefreshSoon();};
        loginTimeout=new DispatcherTimer{Interval=TimeSpan.FromMinutes(5)};loginTimeout.Tick+=async(s,e)=>{loginTimeout.Stop();await Service.CancelLogin();Service.Error="loginExpired";Render();};
        moveTimer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(350)};moveTimer.Tick+=(s,e)=>{moveTimer.Stop();if(!placing&&!manualResize&&!moving)SavePosition();};
        LocationChanged+=(s,e)=>{if(!placing&&!manualResize&&!moving){moveTimer.Stop();moveTimer.Start();}};
        Closing+=(s,e)=>{if(!closing){e.Cancel=true;Hide();}};Closed+=(s,e)=>{poll.Stop();tick.Stop();moveTimer.Stop();loginTimeout.Stop();tray.Visible=false;tray.Dispose();Service.Dispose();SystemEvents.PowerModeChanged-=Power;SystemEvents.DisplaySettingsChanged-=Displays;SystemEvents.UserPreferenceChanged-=Preferences;};
        SystemEvents.PowerModeChanged+=Power;SystemEvents.DisplaySettingsChanged+=Displays;SystemEvents.UserPreferenceChanged+=Preferences;
        Loaded+=async(s,e)=>{PositionInitial();Render();tick.Start();if(!smoke)await Service.Refresh();};
        PreviewMouseRightButtonUp+=(s,e)=>{ShowMenu();e.Handled=true;};KeyDown+=(s,e)=>{if(e.Key==Key.Escape&&view=="settings"){view="main";Render();}};
        if(J.B(Service.Settings,"startup")&&!smoke)SetStartup(true);
    }
    public static string Resource(string name){using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream(name))using(var r=new StreamReader(s))return r.ReadToEnd();}
    string T(string key){return Localization.Text(J.S(Service.Settings,"language","zh"),key);}
    bool Zh {get{return J.S(Service.Settings,"language")!="en";}}
    void SetLanguage(string language){if(!Localization.Codes.Contains(language))return;Service.Settings["language"]=language;Service.Save();Render();}
    ContextMenu LanguageMenu(FrameworkElement anchor){var menu=new ContextMenu{PlacementTarget=anchor,Placement=PlacementMode.Bottom,MinWidth=154,FontSize=12,Background=surface,Foreground=ink};
        for(int i=0;i<Localization.Codes.Length;i++){string code=Localization.Codes[i];var item=new MenuItem{Header=Localization.Names[i],IsCheckable=true,IsChecked=J.S(Service.Settings,"language")==code,Padding=new Thickness(8,6,8,6)};item.Click+=(s,e)=>SetLanguage(code);menu.Items.Add(item);}return menu;
    }
    void Power(object s,PowerModeChangedEventArgs e){Dispatcher.BeginInvoke(new Action(async()=>{if(e.Mode==PowerModes.Suspend){poll.Stop();Service.Rpc.Stop();}else if(e.Mode==PowerModes.Resume)await Service.Refresh();}));}
    void Displays(object s,EventArgs e){Dispatcher.BeginInvoke(new Action(()=>{KeepOnScreen();Render();}));}
    void Preferences(object s,UserPreferenceChangedEventArgs e){if(J.S(Service.Settings,"theme")=="system")Dispatcher.BeginInvoke(new Action(Render));}
    async void RefreshSoon(){if(!closing)await Service.Refresh();}
    void OnServiceChanged(){if(closing)return;if(Service.Identity==null){dailyOpen=false;otherOpen=false;}if((view!="settings"||draftAccount!=Service.Identity)&&!manualResize)Render();if(!Service.Busy){double seconds=J.N(Service.Settings,"refreshSeconds",120);poll.Interval=TimeSpan.FromSeconds(Math.Min(1800,Math.Max(seconds,IsVisible?seconds:600)*Math.Pow(2,Math.Min(3,Service.Failures))));if(!smoke)poll.Start();}}
    public void Reveal(){Show();Activate();KeepOnScreen();if(!Service.Busy&&(Service.Snapshot==null||J.Now-J.N(Service.Snapshot,"observedAt")>J.N(Service.Settings,"refreshSeconds",120)*1000))RefreshSoon();}
    public void Quit(){closing=true;Close();Application.Current.Shutdown();}
    void Colors(){var culture=Localization.Culture(J.S(Service.Settings,"language"));System.Threading.Thread.CurrentThread.CurrentCulture=culture;System.Threading.Thread.CurrentThread.CurrentUICulture=culture;Language=System.Windows.Markup.XmlLanguage.GetLanguage(culture.Name);dark=J.S(Service.Settings,"theme")=="dark";if(J.S(Service.Settings,"theme")=="system"){using(var key=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"))dark=key!=null&&Convert.ToInt32(key.GetValue("AppsUseLightTheme",1))==0;}
        ink=Paint.Brush(dark?"#E9F1FF":"#1E2D45");muted=Paint.Brush(dark?"#94A6BF":"#758398");accent=Paint.Brush(J.S(Service.Settings,"accentColor",dark?"#659DF7":"#4C8DF3"));line=Paint.Brush(dark?"#35445A":"#DFE7F1");surface=Paint.Brush(dark?"#24354C":"#FAFCFF");Foreground=ink;
        Resources["Ink"]=ink;Resources["Muted"]=muted;Resources["Surface"]=surface;Resources["Line"]=line;Resources["Accent"]=accent;}
    TextBlock Text(string text,double size=12,Brush color=null,bool bold=false){return new TextBlock{Text=text??"",FontSize=size,Foreground=color??ink,FontWeight=bold?FontWeights.SemiBold:FontWeights.Normal,TextWrapping=TextWrapping.Wrap,VerticalAlignment=VerticalAlignment.Center};}
    Button Button(string label,Action action,Brush color=null){var b=new Button{Content=label,Foreground=color??accent,Padding=new Thickness(7,5,7,5),Cursor=Cursors.Hand};b.Click+=(s,e)=>action();return b;}
    Button IconButton(string glyph,string tooltip,Action action,bool selected=false){var b=Button(glyph,action,selected?accent:muted);b.FontFamily=new FontFamily("Segoe MDL2 Assets");b.FontSize=16;b.Width=29;b.Height=30;b.Padding=new Thickness(0);b.ToolTip=tooltip;System.Windows.Automation.AutomationProperties.SetName(b,tooltip);return b;}
    StackPanel Stack(params UIElement[] elements){var s=new StackPanel();foreach(var e in elements)if(e!=null)s.Children.Add(e);return s;}
    Grid Row(UIElement left,UIElement right){var g=new Grid();g.ColumnDefinitions.Add(new ColumnDefinition());g.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});g.Children.Add(left);if(right!=null){Grid.SetColumn(right,1);g.Children.Add(right);}return g;}
    Border Card(UIElement content,bool primary=false){return new Border{CornerRadius=new CornerRadius(15),Background=primary?new SolidColorBrush(Color.FromArgb(dark?(byte)36:(byte)18,((SolidColorBrush)accent).Color.R,((SolidColorBrush)accent).Color.G,((SolidColorBrush)accent).Color.B)):surface,BorderBrush=primary?new SolidColorBrush(Color.FromArgb(55,((SolidColorBrush)accent).Color.R,((SolidColorBrush)accent).Color.G,((SolidColorBrush)accent).Color.B)):line,BorderThickness=new Thickness(1),Padding=new Thickness(16),Margin=new Thickness(0,0,0,12),Child=content};}
    Border Divider(){return new Border{Height=1,Background=line,Margin=new Thickness(0,8,0,8)};}
    bool moving,renderAfterMove;string scrollView;
    public void Render(){if(moving){renderAfterMove=true;return;}if(manualResize)return;double scrollOffset=scroller!=null&&scrollView==view?scroller.VerticalOffset:0;double oldWidth=Width;Rect oldArea=WorkArea();bool anchorRight=!double.IsNaN(Left)&&Left+oldWidth/2>oldArea.Left+oldArea.Width/2;Colors();clockUpdates.Clear();ring=null;Topmost=J.B(Service.Settings,"pinned",true);placing=true;
        bool mini=view=="main"&&J.B(Service.Settings,"compact");
        if(mini){Width=92;Height=126;BuildRing();}else{
            var saved=J.Get(Service.Settings,"mainSize");Width=view=="settings"?382:saved==null?382:J.N(saved,"width",382);
            Height=view=="settings"?740:saved==null?580:J.N(saved,"height",580);var area=WorkArea();Width=Math.Min(Width,area.Width);Height=Math.Min(Height,area.Height);
            var outer=new Grid{Margin=new Thickness(10)};var body=new Grid();body.RowDefinitions.Add(new RowDefinition{Height=new GridLength(56)});body.RowDefinitions.Add(new RowDefinition());if(view=="main")body.RowDefinitions.Add(new RowDefinition{Height=new GridLength(44)});
            var background=new LinearGradientBrush(dark?Color.FromRgb(33,48,69):Color.FromRgb(250,252,255),dark?Color.FromRgb(25,41,59):Color.FromRgb(233,243,255),55);
            var frame=new Border{CornerRadius=new CornerRadius(22),Background=background,BorderBrush=dark?Paint.Brush("#4A5A6E"):Brushes.White,BorderThickness=new Thickness(1),Child=body};outer.Children.Add(frame);
            body.Children.Add(Header());scroller=new ScrollViewer{Style=(Style)Resources["WidgetScrollViewer"],VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled,Padding=new Thickness(20,20,20,8),Content=view=="settings"?SettingsView():Overview()};scrollView=view;Grid.SetRow(scroller,1);body.Children.Add(scroller);
            if(view=="main"){var footer=Footer();Grid.SetRow(footer,2);body.Children.Add(footer);AddCorners(outer);}
            Content=outer;
            scroller.ScrollToVerticalOffset(scrollOffset);
        }
        if(anchorRight)Left+=oldWidth-Width;KeepOnScreen();placing=false;UpdateTray();}
    UIElement Header(){var g=new Grid{Margin=new Thickness(15,0,15,0)};g.ColumnDefinitions.Add(new ColumnDefinition());g.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});
        if(view=="settings"){var a=new StackPanel{Orientation=Orientation.Horizontal};a.Children.Add(IconButton("\uE72B",T("back"),()=>{view="main";Render();}));a.Children.Add(Text(T("settingsTitle"),16,null,true));g.Children.Add(a);var v=Text("v"+Version,10,muted);Grid.SetColumn(v,1);g.Children.Add(v);}else{
            var brand=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var image=new Image{Source=IconSource(),Width=27,Height=27,Margin=new Thickness(0,0,9,0)};brand.Children.Add(image);brand.Children.Add(Text("Codex Glass",12,null,true));g.Children.Add(brand);
            var nav=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};Button lang=null;lang=Button((J.S(Service.Settings,"language")=="zh"?"简":J.S(Service.Settings,"language")=="zh-TW"?"繁":"EN")+" ▾",()=>{var menu=LanguageMenu(lang);menu.IsOpen=true;},muted);lang.FontSize=10;lang.Width=37;lang.Padding=new Thickness(0);lang.ToolTip=T("language");System.Windows.Automation.AutomationProperties.SetName(lang,T("language"));nav.Children.Add(lang);nav.Children.Add(IconButton("\uE718",T(J.B(Service.Settings,"pinned")?"unpin":"pin"),()=>{Service.Settings["pinned"]=!J.B(Service.Settings,"pinned");Service.Save();Render();},J.B(Service.Settings,"pinned")));nav.Children.Add(IconButton("\uE713",T("settings"),()=>{view="settings";Render();}));nav.Children.Add(IconButton("\uE923",T("compact"),()=>Compact(true)));Grid.SetColumn(nav,1);g.Children.Add(nav);
        }
        // A transparent background makes the entire title bar (including its padding) hit-testable.
        var header=new Border{Name="TitleBar",Background=Brushes.Transparent,BorderBrush=line,BorderThickness=new Thickness(0,0,0,1),Child=g};
        header.PreviewMouseLeftButtonDown+=(s,e)=>{if(HeaderDragTarget(e.OriginalSource as DependencyObject,header)){e.Handled=true;MoveWindow();}};
        return header;}
    static bool HeaderDragTarget(DependencyObject source,DependencyObject header){
        for(var current=source;current!=null;){
            if(current is ButtonBase)return false;
            if(current==header)return true;
            var content=current as FrameworkContentElement;
            current=content!=null?content.Parent:VisualTreeHelper.GetParent(current);
        }
        return false;
    }
    void MoveWindow(){if(moving||Mouse.LeftButton!=MouseButtonState.Pressed)return;moveTimer.Stop();moving=true;
        try{DragMove();}catch(InvalidOperationException){/* The button can be released before the native move loop begins. */}
        finally{moving=false;SavePosition();if(renderAfterMove){renderAfterMove=false;Render();}}
    }
    ImageSource IconSource(){return this.Icon;}
    UIElement Overview(){var panel=new StackPanel();var title=Row(Text(T("title"),21,null,true),Service.Snapshot==null?null:new Border{Background=new SolidColorBrush(Color.FromArgb(24,80,140,240)),CornerRadius=new CornerRadius(6),Padding=new Thickness(10,4,10,4),Child=Text(Model.Plan(J.Get(Service.Snapshot,"plan")),11,accent)});title.Margin=new Thickness(0,0,0,20);panel.Children.Add(title);
        if(Service.Demo)panel.Children.Add(new Border{Background=Paint.Brush(dark?"#4B4130":"#F6F1E6"),CornerRadius=new CornerRadius(5),Padding=new Thickness(5),Margin=new Thickness(0,0,0,12),Child=Text(T("demo"),10,Paint.Brush("#A47A32"))});
        if(Service.Snapshot==null){panel.Children.Add(Text(T("connectTitle"),17,null,true));panel.Children.Add(Text(T("connectBody"),12,muted));var error=Text(T(Service.Error??"syncing"),12,muted);error.Margin=new Thickness(0,18,0,14);panel.Children.Add(error);panel.Children.Add(Button(T(Service.Error=="codexMissing"?"install":Service.LoginId==null?"connect":"cancel"),async()=>{if(Service.Error=="codexMissing")Open("https://developers.openai.com/codex/cli");else if(Service.LoginId!=null)await Service.CancelLogin();else{string url=await Service.Login();if(url!=null){Open(url);loginTimeout.Start();}}}));panel.Children.Add(Button(T("retry"),RefreshSoon));panel.Children.Add(Text(T("sharedLogin"),10,muted));return panel;}
        var main=J.Items(Service.Snapshot["windows"]).Where(w=>J.S(w,"group")=="codex").ToArray();if(main.Length==0)panel.Children.Add(Text(T("noWindows"),12,muted));for(int i=0;i<main.Length;i++)panel.Children.Add(Quota(main[i],i==0));
        var others=J.Items(Service.Snapshot["windows"]).Where(w=>J.S(w,"group")!="codex").GroupBy(w=>J.S(w,"group")).ToArray();
        if(others.Length>0){panel.Children.Add(Divider());var toggle=Button("",()=>{otherOpen=!otherOpen;Render();},muted);toggle.HorizontalContentAlignment=HorizontalAlignment.Stretch;toggle.Padding=new Thickness(0,8,0,10);
            var badge=new Border{Background=surface,CornerRadius=new CornerRadius(5),Padding=new Thickness(5,1,5,1),Child=Text(others.Length.ToString(),10,muted)};
            toggle.Content=Row(Text((otherOpen?"▾ ":"▸ ")+T("otherPools"),11,muted),badge);System.Windows.Automation.AutomationProperties.SetName(toggle,T("otherPools")+" "+others.Length);panel.Children.Add(toggle);
            if(otherOpen){var help=Text(T("poolHelp"),10,muted);help.Margin=new Thickness(0,2,0,14);help.LineHeight=16;panel.Children.Add(help);
                foreach(var group in others){string model=J.S(group.First(),"model");if(model!=""){var label=Text(model,11);label.Margin=new Thickness(0,0,0,8);panel.Children.Add(label);}foreach(var q in group)panel.Children.Add(Quota(q,false));}
            }
        }
        panel.Children.Add(Divider());var dailyToggle=Button((dailyOpen?"▾  ":"▸  ")+T("dailyTokens"),async()=>{dailyOpen=!dailyOpen;Render();if(dailyOpen)await Service.ReadDaily();});dailyToggle.HorizontalContentAlignment=HorizontalAlignment.Left;dailyToggle.Padding=new Thickness(0,8,0,10);panel.Children.Add(dailyToggle);if(dailyOpen)panel.Children.Add(DailyView());panel.Children.Add(Divider());
        object reset=Service.Snapshot["resets"];var resetLabel=Stack(Text(T("resetCredits"),12),Text(J.Num(J.Get(reset,"expiresAt")).HasValue?J.Time(J.N(reset,"expiresAt")).ToString(Zh?"yyyy年M月d日":"MMM d, yyyy")+" "+T("expires"):T("unknown"),10,muted));var resetRight=new StackPanel{Orientation=Orientation.Horizontal};resetRight.Children.Add(Text((J.Get(reset,"count")==null?"—":J.N(reset,"count").ToString("0"))+" "+T("times"),23,null,true));var resetButton=Button(T("resetAction")+" ↗",()=>Open("https://chatgpt.com/codex/settings/usage"));resetButton.Margin=new Thickness(7,0,0,0);resetButton.FontSize=10;resetButton.ToolTip=T("resetHelp");resetRight.Children.Add(resetButton);var resetRow=Row(resetLabel,resetRight);resetRow.Margin=new Thickness(0,10,0,10);panel.Children.Add(resetRow);panel.Children.Add(Divider());
        var member=Service.Member;string date=J.S(member,"date");var info=new StackPanel();info.Children.Add(Text(T(date==""?"membership":J.S(member,"kind"))+ (date==""?"":"  · "+T("manualShort")),11,muted));info.Children.Add(Text(date==""?T("unknown"):DateTime.ParseExact(date,"yyyy-MM-dd",CultureInfo.InvariantCulture).ToString(Zh?"yyyy年M月d日":"MMM d, yyyy"),12,null,true));if(date!=""){int days=(DateTime.ParseExact(date,"yyyy-MM-dd",CultureInfo.InvariantCulture)-DateTime.Today).Days;info.Children.Add(Text(days<0?T("datePassed"):days==0?T("today"):days+" "+T("daysLeft"),10,muted));}var memberRow=Row(info,Button(T(date==""?"setDate":"edit"),()=>{view="settings";Render();}));memberRow.Margin=new Thickness(0,7,0,10);panel.Children.Add(memberRow);return panel;}
    string QuotaName(object q){return J.N(q,"minutes")==10080?T("week"):J.N(q,"minutes")==300?T("five"):J.N(q,"minutes")>0?J.N(q,"minutes")+" "+T("minutes"):"Codex";}
    string Countdown(object q){double? time=J.Num(J.Get(q,"resetsAt"));if(!time.HasValue)return T("noReset");double minutes=Math.Ceiling((time.Value-J.Now)/60000);if(minutes<=0)return T("resetting");int days=(int)(minutes/1440),hours=(int)(minutes%1440/60),mins=(int)(minutes%60);return (days>0?days+" "+T("days")+" "+hours+" "+T("hours"):hours>0?hours+" "+T("hours")+" "+mins+" "+T("minutes"):mins+" "+T("minutes"))+" "+T("resetsIn");}
    UIElement Quota(object q,bool primary){var name=new StackPanel{Orientation=Orientation.Horizontal};var calendar=Text("\uE787",13,muted);calendar.FontFamily=new FontFamily("Segoe MDL2 Assets");calendar.Margin=new Thickness(0,0,8,0);name.Children.Add(calendar);name.Children.Add(Text(QuotaName(q),12,null,true));if(J.S(q,"scope")!=""){var scope=Text(J.S(q,"scope"),10,muted);scope.Margin=new Thickness(7,0,0,0);name.Children.Add(scope);}var top=Row(name,Text(T("remaining"),10,muted));bool expired=J.N(q,"resetsAt")>0&&J.N(q,"resetsAt")<=J.Now;
        var number=Text(expired?"—":Math.Floor(J.N(q,"remaining")).ToString(),39,null,true);var suffix=Text(expired?"":"%",20,muted);var remaining=Text(expired?"":T("remaining"),10,muted);suffix.VerticalAlignment=remaining.VerticalAlignment=VerticalAlignment.Bottom;suffix.Margin=new Thickness(0,0,0,6);remaining.Margin=new Thickness(6,0,0,7);var amount=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,8,0,8)};amount.Children.Add(number);amount.Children.Add(suffix);amount.Children.Add(remaining);
        var track=new Grid{Height=5,Background=line,Margin=new Thickness(0,0,0,10)};double percent=expired?0:J.N(q,"remaining");track.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(Math.Max(.00001,percent),GridUnitType.Star)});track.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(Math.Max(.00001,100-percent),GridUnitType.Star)});if(percent>0)track.Children.Add(new Border{Background=percent<=10?Paint.Brush("#EB7165"):accent,CornerRadius=new CornerRadius(3)});
        var countdown=Text(Countdown(q),10,muted);clockUpdates.Add(()=>{countdown.Text=Countdown(q);if(J.N(q,"resetsAt")>0&&J.N(q,"resetsAt")<=J.Now){number.Text="—";suffix.Text=remaining.Text="";}});Button pin=null;if(J.S(q,"group")=="codex"&&new[]{300d,10080d}.Contains(J.N(q,"minutes"))){string which=J.N(q,"minutes")==300?"five":"week";pin=IconButton("\uE718",T("pinWindow"),()=>{Service.Settings["ringWindow"]=J.S(Service.Settings,"ringWindow")==which?"auto":which;Service.Save();Render();},J.S(Service.Settings,"ringWindow")==which);pin.Width=22;pin.Height=22;pin.FontSize=12;}return Card(Stack(top,amount,track,Row(countdown,pin)),primary);}
    UIElement DailyView(){var content=new StackPanel();var switches=new StackPanel{Orientation=Orientation.Horizontal};foreach(int n in new[]{7,30}){int captured=n;var b=Button(n+T("dayRange"),()=>{range=captured;Render();},range==n?accent:muted);b.FontSize=10;b.Background=range==n?surface:Brushes.Transparent;switches.Children.Add(b);}var refresh=Button(T("dailyRefresh"),async()=>await Service.ReadDaily());refresh.FontSize=10;content.Children.Add(Row(switches,refresh));
        if(Service.DailyBusy||Service.DailyError!=null||!J.Items(J.Get(Service.Daily,"days")).Any()){var msg=Text(T(Service.DailyBusy?"syncing":Service.DailyError??"noDaily"),11,muted);msg.Margin=new Thickness(0,14,0,8);content.Children.Add(msg);}else{var days=Model.Series(Service.Daily,range,DateTime.Today);var known=days.Where(d=>J.Get(d,"tokens")!=null).ToArray();var total=Row(Text(T("periodTokens"),10,muted),Text(known.Length==0?"—":known.Sum(d=>J.N(d,"tokens")).ToString("N0"),17,null,true));total.Margin=new Thickness(0,12,0,10);content.Children.Add(total);content.Children.Add(new BarChart(days,accent,muted));}
        var note=Text(T("dailySource")+(J.B(Service.Daily,"incomplete")?" "+T("partialDaily"):""),10,muted);note.Margin=new Thickness(0,10,0,8);content.Children.Add(note);return content;}
    UIElement Footer(){statusText=Text("",10,muted);Action update=()=>{string age=Service.Snapshot==null?"":J.Now-J.N(Service.Snapshot,"observedAt")<60000?T("justNow"):Math.Floor((J.Now-J.N(Service.Snapshot,"observedAt"))/60000)+" "+T("minutesAgo");statusText.Text="●  "+T(Service.Busy?"syncing":Service.Status=="live"?"live":Service.Status=="stale"?"stale":"offline")+"  "+age;};update();clockUpdates.Add(update);var buttons=new StackPanel{Orientation=Orientation.Horizontal};buttons.Children.Add(IconButton("\uE72C",T("refresh"),RefreshSoon));buttons.Children.Add(IconButton("\uE8A7",T("usage"),()=>Open("https://chatgpt.com/codex/settings/usage")));return new Border{BorderBrush=line,BorderThickness=new Thickness(0,1,0,0),Padding=new Thickness(20,2,14,2),Child=Row(statusText,buttons)};}
    void Compact(bool compact){Service.Settings["compact"]=compact;Service.Save();view="main";Render();}
    void BuildRing(){var selected=Model.Selected(Service.Snapshot,J.S(Service.Settings,"ringWindow"),J.Now);ring=new RingView{Quota=selected,Period=selected==null?"":QuotaName(selected),Accent=J.Get(Service.Settings,"accentColor")==null?Paint.Brush("#2EC9A0"):accent,Stale=Service.Status=="stale",Demo=Service.Demo,Outer=J.B(Service.Settings,"elapsedArc"),OuterAccent=accent,Logo=logo};ring.ToolTip=string.Join("\n",J.Items(J.Get(Service.Snapshot,"windows")).Select(q=>QuotaName(q)+" · "+Math.Floor(J.N(q,"remaining"))+"% · "+Countdown(q)))+"\n"+T("ringHelp");ring.MouseLeftButtonDown+=(s,e)=>{ringDown=PointToScreen(e.GetPosition(this));ringMoved=false;ring.CaptureMouse();e.Handled=true;};ring.MouseMove+=(s,e)=>{if(e.LeftButton!=MouseButtonState.Pressed)return;Point p=PointToScreen(e.GetPosition(this));if(!ringMoved&&(p-ringDown).Length>5){ringMoved=true;ring.ReleaseMouseCapture();MoveWindow();}};ring.MouseLeftButtonUp+=(s,e)=>{ring.ReleaseMouseCapture();if(!ringMoved)Compact(false);e.Handled=true;};ring.KeyDown+=(s,e)=>{if(e.Key==Key.Enter||e.Key==Key.Space){Compact(false);e.Handled=true;}};Content=ring;}
    public static void Open(string url){Process.Start(new ProcessStartInfo(url){UseShellExecute=true});}
    void SetStartup(bool enabled){if(smoke)return;try{using(var key=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run")){if(enabled)key.SetValue("Codex Glass","\""+Assembly.GetExecutingAssembly().Location+"\" --hidden");else key.DeleteValue("Codex Glass",false);}}catch{Service.Settings["startup"]=false;}}
    void UpdateTray(){tray.Text="Codex Glass";var menu=new Forms.ContextMenuStrip();Action<string,Action> item=(label,action)=>menu.Items.Add(label,null,(s,e)=>Dispatcher.BeginInvoke(action));item(T("expand"),()=>{Compact(false);Reveal();});item(T("compact"),()=>{Compact(true);Reveal();});item(T("settings"),()=>{view="settings";Render();Reveal();});item(T("refresh"),RefreshSoon);item(T("restoreSize"),()=>{Service.Settings["mainSize"]=null;Service.Save();Render();});item(T("quit"),Quit);var old=tray.ContextMenuStrip;tray.ContextMenuStrip=menu;if(old!=null)old.Dispose();}
    void ShowMenu(){var menu=new ContextMenu();Action<string,Action> item=(label,action)=>{var m=new MenuItem{Header=label};m.Click+=(s,e)=>action();menu.Items.Add(m);};item(T("expand"),()=>Compact(false));item(T("settings"),()=>{view="settings";Render();});item(T("refresh"),RefreshSoon);item(T("restoreSize"),()=>{Service.Settings["mainSize"]=null;Service.Save();Render();});item(T("quit"),Quit);menu.IsOpen=true;}
    Rect WorkArea(){var source=PresentationSource.FromVisual(this);var area=Forms.Screen.FromHandle(new System.Windows.Interop.WindowInteropHelper(this).Handle).WorkingArea;var transform=source==null?Matrix.Identity:source.CompositionTarget.TransformFromDevice;Point a=transform.Transform(new Point(area.Left,area.Top)),b=transform.Transform(new Point(area.Right,area.Bottom));return new Rect(a,b);}
    void PositionInitial(){var pos=J.Get(Service.Settings,"position");var a=WorkArea();placing=true;Left=pos==null?a.Right-Width-24:J.N(pos,"x");Top=pos==null?a.Top+48:J.N(pos,"y");placing=false;KeepOnScreen();}
    void KeepOnScreen(){if(double.IsNaN(Left)||double.IsNaN(Top))return;Rect a=WorkArea();Left=Math.Max(a.Left,Math.Min(Left,a.Right-Width));Top=Math.Max(a.Top,Math.Min(Top,a.Bottom-Height));}
    void SavePosition(){var a=WorkArea();placing=true;if(Math.Abs(Left-a.Left)<20)Left=a.Left;if(Math.Abs(Left+Width-a.Right)<20)Left=a.Right-Width;if(Math.Abs(Top-a.Top)<20)Top=a.Top;if(Math.Abs(Top+Height-a.Bottom)<20)Top=a.Bottom-Height;KeepOnScreen();Service.Settings["position"]=J.Obj("x",Left,"y",Top);Service.Save();placing=false;}
    void AddCorners(Grid root){foreach(string corner in new[]{"nw","ne","sw","se"}){string c=corner;var thumb=new Thumb{Width=24,Height=24,HorizontalAlignment=c.Contains("w")?HorizontalAlignment.Left:HorizontalAlignment.Right,VerticalAlignment=c.Contains("n")?VerticalAlignment.Top:VerticalAlignment.Bottom,Cursor=c=="nw"||c=="se"?Cursors.SizeNWSE:Cursors.SizeNESW,Background=Brushes.Transparent,Template=(ControlTemplate)Resources["ResizeThumb"]};Rect origin=new Rect();Point start=new Point();thumb.DragStarted+=(s,e)=>{manualResize=true;origin=new Rect(Left,Top,Width,Height);start=CursorPoint();};thumb.DragDelta+=(s,e)=>{Point current=CursorPoint();ResizeFrom(origin,c,current.X-start.X,current.Y-start.Y);};thumb.DragCompleted+=(s,e)=>{manualResize=false;Service.Settings["mainSize"]=J.Obj("width",Width,"height",Height);SavePosition();Render();};root.Children.Add(thumb);}}
    [StructLayout(LayoutKind.Sequential)]struct NativePoint{public int X,Y;}
    [DllImport("user32.dll")]static extern bool GetCursorPos(out NativePoint p);
    Point CursorPoint(){NativePoint p;GetCursorPos(out p);var source=PresentationSource.FromVisual(this);return source.CompositionTarget.TransformFromDevice.Transform(new Point(p.X,p.Y));}
    void ResizeFrom(Rect origin,string corner,double dx,double dy){Rect a=WorkArea();bool west=corner.Contains("w"),north=corner.Contains("n");double maxW=Math.Min(900,west?origin.Right-a.Left:a.Right-origin.Left),maxH=Math.Min(1400,north?origin.Bottom-a.Top:a.Bottom-origin.Top);Width=J.Clamp(origin.Width+(west?-dx:dx),Math.Min(320,maxW),maxW);Height=J.Clamp(origin.Height+(north?-dy:dy),Math.Min(360,maxH),maxH);Left=west?origin.Right-Width:origin.Left;Top=north?origin.Bottom-Height:origin.Top;}
}
}
